add GenderCardView
AdrianLunaVillegas/first-project-android pull request #1
Opened 2023-07-21 11:47 UTC by AdrianLunaVillegas

create a gendercardview to optimize the code

2023-07-21 12:15 UTC, xavijimenezmulet requested changes

2023-07-21 12:15 UTC, xavijimenezmulet commented on app/src/main/AndroidManifest.xml
> +
You should use just a one blank space.

2023-07-21 12:15 UTC, xavijimenezmulet commented on app/src/main/java/com/adriandevs/androidmaster1/firstapp/common/GenderCardView.kt
> +        binding.apply {
Put this in a function, some like initData()

2023-07-21 12:15 UTC, xavijimenezmulet commented on app/src/main/res/layout/activity_gender.xml
Why is this unused xml?

2023-07-21 14:45 UTC, jose-ojalvo commented on app/src/main/res/layout/card_view_gender.xml
> +        android:id="@+id/gMale"
View IDs should describe briefly the purpose of the view, avoid describing the use case nor the implementation. 

Please modify the IDs to match the usage (e.g genderImage instead of gMale)

2023-07-21 14:46 UTC, jose-ojalvo commented on app/src/main/res/layout/card_view_gender.xml
> +        android:id="@+id/tvMale"
Same as stated above, avoid using the use case of the component for the naming of its views, it will lead to misleading use of this view.

2023-07-21 14:48 UTC, jose-ojalvo commented on app/src/main/res/values/attrs.xml
> +        <attr name="customImage" format="reference" />
Just as a warning, don't use generic parameter names in the styleable attributes because the names cannot be reused in another style declaration.

Take that into account when naming attributes (you won't be able to use "customImage" in another style).

2023-07-21 14:52 UTC, jose-ojalvo commented on app/src/main/AndroidManifest.xml
> +            android:exported="false" />
Why did you add a custom view as an activity in the manifest??
Also, does your activities allow orientation switching? Be mindful of that behavior as it can break your app

2023-07-23 10:14 UTC, jose-ojalvo requested changes
There are still changes to be made in order to merge this pull request to master, please take a look at what's still remaining

2023-07-26 11:47 UTC, xavijimenezmulet requested changes

2023-07-26 11:47 UTC, xavijimenezmulet commented on app/src/main/java/com/adriandevs/androidmaster1/todoapp/CategoriesViewHolder.kt
> +            tvCategoryName.text = "EXEMPLE"
Why is this string is hardcoded?

2023-07-26 11:47 UTC, xavijimenezmulet commented on app/src/main/java/com/adriandevs/androidmaster1/todoapp/TasksAdapter.kt
> +        val view =
Why you are not using view binding ?

2023-07-26 11:47 UTC, xavijimenezmulet commented on app/src/main/java/com/adriandevs/androidmaster1/todoapp/TasksViewHolder.kt
> +
Why it's empty ?

2023-07-31 11:40 UTC, xavijimenezmulet approved these changes

2023-07-31 11:41 UTC, xavijimenezmulet approved these changes

2023-07-31 11:42 UTC, merged